### ISSUE TITLE
v2.0.0: Cost long time after updating to a .jsx file

### ISSUE THREAD

**Issue by wxqee** [rdev/expressx#1]
I found that when I update a JSX file and trigger rebuild by change `webcomponent/index.js`, it takes too long time to wait on web page. BTW, it seems like the initial loading takes long time as well after I see the 3000 port has been listened.

**Comment by rdev** [comment]
When building the frontend, expressx invokes webpack directly (or via middleware if the corresponding config option is set). The time it takes to build depends on the amount of files webpack needs to process.
By default it runs webpack in "direct" mode, which works well for small codebases, but for large frontend-heavy projects it's better to set
```js
webpackMode: 'middleware'
```
in `expressx.config.js` as subsequent builds are usually faster through `webpack-dev-middleware`.

In terms of initial loading, expressx doesn't really have anything to do with that. The moment you see the **`> Ready on port XXXX`** everything build-related has been done and the server started listening. Except if webpack mode is set to "middleware", because middleware is only able to build frontend *after* the server started listening and it will halt requests until build is ready.
